apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/anomaly51/general-1-argocd.git
    targetRevision: main
    path: apps/dependency-demo
    helm:
      releaseName: dependency-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: dependency-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
