image:
  repository: busybox
  digest: sha256:9db7b59979c38555a39def84a31fb98b5296952f9e3afd4f6f11f05b07adfab0
  pullPolicy: IfNotPresent

vault:
  role: apps-vault-demo
  mount: kv
  path: apps/vault-demo

secret:
  name: vault-demo
  key: message

service:
  port: 80

resources:
  requests:
    cpu: 5m
    memory: 8Mi
  limits:
    cpu: 50m
    memory: 32Mi
