vaultSecrets:
  enabled: true
  authGlobalNamespace: vault-system
  bindings:
    - name: vault-demo
      authName: vault-demo
      serviceAccountName: vso-vault-demo
      role: apps-vault-demo
      path: apps/vault-demo
      refreshAfter: 10s
