opentelemetry-operator:
  fullnameOverride: opentelemetry-operator
  nodeSelector:
    kubernetes.io/hostname: general-1-worker-2
  manager:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
  admissionWebhooks:
    certManager:
      enabled: true
