apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-service-account-reader
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-service-account-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-service-account-reader
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault-system
