apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: uptime-monitor-rabbitmq-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: uptime-monitor
  mount: {{ .Values.vault.mount }}
  type: kv-v2
  path: {{ .Values.vault.envPath }}
  refreshAfter: {{ .Values.vault.refreshAfter }}
  destination:
    create: true
    name: uptime-monitor-rabbitmq-credentials
    labels:
      rabbitmq.com/topology-operator: "true"
    transformation:
      excludes:
        - .*
      templates:
        username:
          text: '{{ `{{- get .Secrets "RABBITMQ_USERNAME" -}}` }}'
        password:
          text: '{{ `{{- get .Secrets "RABBITMQ_PASSWORD" -}}` }}'
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: uptime-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: uptime-monitor
  defaultQueueType: quorum
  deletionPolicy: retain
  rabbitmqClusterReference:
    name: shared
    namespace: rabbitmq-system
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: uptime-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  importCredentialsSecret:
    name: uptime-monitor-rabbitmq-credentials
  rabbitmqClusterReference:
    name: shared
    namespace: rabbitmq-system
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: uptime-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  vhost: uptime-monitor
  userReference:
    name: uptime-monitor
  permissions:
    configure: ".*"
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: shared
    namespace: rabbitmq-system
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: uptime-monitor-checks
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: monitor_checks
  vhost: uptime-monitor
  type: quorum
  durable: true
  autoDelete: false
  deletionPolicy: retain
  rabbitmqClusterReference:
    name: shared
    namespace: rabbitmq-system
