apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets
automountServiceAccountToken: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: arc-runners
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: arc-runners
    serviceAccount: vault-secrets
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: arc-github-token
spec:
  vaultAuthRef: arc-runners
  mount: kv
  type: kv-v2
  path: ci/arc-github
  refreshAfter: 1m
  destination:
    create: true
    name: arc-github-token
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        github_token:
          text: '{{ `{{ get .Secrets "token" }}` }}'
