_release:
  revision: 18fd5c4b14762722c3f4edb89aea8062739c28df
  sourceRepository: anomaly51/uptime-monitor
  sourceCommit: 3a4aea887928bdee1d82920dda164e3264edf781
  sourceBranch: dev
  runUrl: https://github.com/anomaly51/uptime-monitor/actions/runs/36481049584
  imageKeys:
  - images.api
  - images.frontend
images:
  api:
    repository: harbor.internal.api-api-api.com/applications/uptime-monitor-api
    tag: sha-3a4aea887928@sha256:08c0ac9384d009036461dc8912fcdb21ed6427c63fb745d0fe53bfcb4b7d8daf
    pullPolicy: IfNotPresent
  frontend:
    repository: harbor.internal.api-api-api.com/applications/uptime-monitor-frontend
    tag: sha-3a4aea887928@sha256:5c0e184dfc0eb5b11c65918e7d1cbdf1d22dda20481aaab7e6ca769d3b27cacc
    pullPolicy: IfNotPresent
  postgres:
    repository: docker.io/library/postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
registry:
  server: harbor.internal.api-api-api.com
  vaultPath: apps/uptime-monitor/dev/registry
vault:
  mount: kv
  authMount: kubernetes
  role: uptime-monitor-dev
  envPath: apps/uptime-monitor/dev/env
  refreshAfter: 1m
routes:
  gatewayName: public
  gatewayNamespace: networking
  gatewaySectionName: https
  frontendHostname: uptime-dev-general1.api-api-api.com
  apiHostname: uptime-api-dev-general1.api-api-api.com
storage:
  className: nfs-csi
  postgresSize: 2Gi
  legacyRabbitmqSize: 2Gi
resources:
  api:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
  worker:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
  scheduler:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 192Mi
  bot:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 192Mi
  frontend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  postgres:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 384Mi
replicas:
  bot: 0
rabbitmq:
  vhost: uptime-monitor-dev
