apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: logging-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logging-ca
spec:
  isCA: true
  commonName: general-1-logging-ca
  secretName: logging-ca
  duration: 87600h
  renewBefore: 8760h
  privateKey: {algorithm: RSA, size: 2048, encoding: PKCS8}
  issuerRef: {name: logging-selfsigned, kind: Issuer}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: logging-ca
spec:
  ca: {secretName: logging-ca}
---
{{- range $name := list "admin" "dashboards" "security" "viewer" }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: opensearch-{{ $name }}
spec:
  vaultAuthRef: monitoring
  mount: kv
  type: kv-v2
  path: monitoring/opensearch-{{ $name }}
  refreshAfter: 1m
  destination:
    create: true
    name: opensearch-{{ $name }}
---
{{- end }}
