grafana:
  replicas: 1

  useStatefulSet: false
  persistence:
    enabled: false

  service:
    type: ClusterIP

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  testFramework:
    enabled: false

  rbac:
    create: false

  grafana.ini:
    analytics:
      check_for_updates: false
      reporting_enabled: false
    plugins:
      preinstall_disabled: true

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local
          isDefault: true
          editable: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: general-1
          orgId: 1
          folder: General-1
          type: file
          disableDeletion: true
          allowUiUpdates: false
          updateIntervalSeconds: 30
          options:
            path: /var/lib/grafana/dashboards/general-1

  dashboardsConfigMaps:
    general-1: grafana-dashboards
