apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    vault.hashicorp.com/alias-metadata-secret_name: authentik
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: authentik
    serviceAccount: vso-authentik
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: authentik
  mount: kv
  type: kv-v2
  path: authentik/authentik
  refreshAfter: 60s
  hmacSecretData: true
  destination:
    name: authentik-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
  rolloutRestartTargets:
    - kind: Deployment
      name: authentik-server
    - kind: Deployment
      name: authentik-worker
