strimzi-kafka-operator:
  replicas: 1
  watchAnyNamespace: true
  fullReconciliationIntervalMs: 300000
  operationTimeoutMs: 300000
  generateNetworkPolicy: true
  generatePodDisruptionBudget: false
  extraEnvs:
    - name: JAVA_OPTS
      value: -Xms64m -Xmx160m
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
