apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appService.name }}
  namespace: {{ .Values._release.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appService.name }}
    app.kubernetes.io/part-of: playground
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.appService.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.appService.port }}
      targetPort: http
      protocol: TCP
