domain: api-api-api.com
tunnelTarget: 4a29ced3-c1b8-4e6f-885b-8b2caaec2149.cfargotunnel.com
issuer: letsencrypt-production

gateway:
  name: public
  className: traefik
  httpPort: 8000
  httpsPort: 8443
  tlsSecretName: public-gateway-tls

allowedRouteNamespaces:
  label: gateway.api-api-api.com/public
  value: "true"
