apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: playground-image-updater-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: playground-image-updater
  mount: kv
  type: kv-v2
  path: {{ .Values.webhook.vaultPath }}
  refreshAfter: 1m
  destination:
    create: true
    name: argocd-image-updater-secret
    transformation:
      excludeRaw: true
      excludes: [".*"]
      templates:
        webhook.harbor-secret:
          text: '{{ `{{- get .Secrets "secret" -}}` }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: playground-image-updater-controller
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: playground-image-updater-webhook
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
      app.kubernetes.io/instance: image-updater
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: harbor
          podSelector:
            matchLabels:
              app.kubernetes.io/name: harbor
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: [core, jobservice]
      ports:
        - {protocol: TCP, port: 8082}
