product: telegram-swearmoderation-bot
environment: prod
enabled: 'true'
namespace: apps
components:
- component: app
  applicationName: apps-telegram-swearmoderation-bot
  releaseName: telegram-swearmoderation-bot
  chartRepo: https://github.com/anomaly51/general-1-argocd.git
  chartRevision: ccd32793828376539a29048135f6069da9994d6e
  chartPath: apps/telegram-swearmoderation-bot
  chartName: ''
  releaseValues:
    image:
      repository: harbor.internal.api-api-api.com/applications/telegram-swearmoderation-bot
      tag: sha-e9324365a465
      pullPolicy: IfNotPresent
