apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
automountServiceAccountToken: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: keycloak
    serviceAccount: vault-secrets
    audiences: [vault]
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-db
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: keycloak
  mount: kv
  type: kv-v2
  path: keycloak/db
  refreshAfter: 1m
  destination:
    create: true
    name: keycloak-db
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-bootstrap
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: keycloak
  mount: kv
  type: kv-v2
  path: keycloak/bootstrap
  refreshAfter: 1m
  destination:
    create: true
    name: keycloak-bootstrap
    type: Opaque
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: keycloak
  mount: kv
  type: kv-v2
  path: keycloak/backup
  refreshAfter: 1m
  destination:
    create: true
    name: keycloak-backup
    type: Opaque
    transformation:
      excludeRaw: true
