apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: harbor
    serviceAccount: vault-secrets
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: harbor
  mount: kv
  type: kv-v2
  path: harbor/harbor
  refreshAfter: 1m
  destination:
    create: true
    name: harbor-credentials
    transformation:
      excludes:
        - .*
      templates:
        HARBOR_ADMIN_PASSWORD:
          text: '{{ `{{- get .Secrets "admin_password" -}}` }}'
        secretKey:
          text: '{{ `{{- get .Secrets "secret_key" -}}` }}'
        secret:
          text: '{{ `{{- get .Secrets "core_secret" -}}` }}'
        CSRF_KEY:
          text: '{{ `{{- get .Secrets "xsrf_key" -}}` }}'
        JOBSERVICE_SECRET:
          text: '{{ `{{- get .Secrets "jobservice_secret" -}}` }}'
        REGISTRY_HTTP_SECRET:
          text: '{{ `{{- get .Secrets "registry_secret" -}}` }}'
        REGISTRY_PASSWD:
          text: '{{ `{{- get .Secrets "registry_password" -}}` }}'
        REGISTRY_HTPASSWD:
          text: '{{ `{{- get .Secrets "registry_htpasswd" -}}` }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: harbor-core
    - kind: Deployment
      name: harbor-jobservice
    - kind: Deployment
      name: harbor-registry
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-database-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: harbor
  mount: kv
  type: kv-v2
  path: harbor/harbor
  refreshAfter: 1m
  destination:
    create: true
    name: harbor-database-app
    type: kubernetes.io/basic-auth
    transformation:
      excludes:
        - .*
      templates:
        username:
          text: harbor
        password:
          text: '{{ `{{- get .Secrets "database_password" -}}` }}'
