authentik:
  authentik:
    existingSecret:
      secretName: authentik

  global:
    nodeSelector:
      kubernetes.io/hostname: general-1-worker-1

  server:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi

  worker:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
