authentik:
  authentik:
    secret_key: "6987bec4b796e5261e4564f408ea4dfc4a57ee69aff2121ee17ac603d8604354"
    postgresql:
      password: "73625f199dfb5a713fd35a850a9356cd95939beeeb5825f1"

  serviceAccount:
    create: false

  postgresql:
    enabled: true
    auth:
      password: "73625f199dfb5a713fd35a850a9356cd95939beeeb5825f1"
    serviceAccount:
      create: false
    primary:
      networkPolicy:
        enabled: false
      pdb:
        create: false
      persistence:
        storageClass: local-path
        size: 2Gi
