_release:
  revision: d8c9d628773a7e3e2c683915fbb9e102b1fabcaa
  sourceRepository: anomaly51/shisha-guid-frontend
  sourceCommit: 2f3a3d37fe84643226a979eb04c8b3746841e50d
  sourceBranch: main
  runUrl: https://github.com/anomaly51/shisha-guid-frontend/actions/runs/36481479143
  imageKeys:
  - image
replicas: 1
image:
  repository: harbor.internal.api-api-api.com/applications/shisha-guid-frontend
  tag: sha-2f3a3d37fe84@sha256:960d4eeb4af5604fc28cb3f7d4f3b4d3d7394e183c57eca9f23c9c3700bcfbc0
  pullPolicy: IfNotPresent
registry:
  server: harbor.internal.api-api-api.com
  vaultPath: apps/shisha-guide/staging/registry
vault:
  mount: kv
  authMount: kubernetes
  role: shisha-guide-staging-frontend
  envPath: apps/shisha-guide/staging/frontend
  refreshAfter: 1m
route:
  gatewayName: public
  gatewayNamespace: networking
  gatewaySectionName: https
  hostname: shisha-staging-general1.api-api-api.com
service:
  port: 80
  containerPort: 80
config:
  publicSiteUrl: https://shisha-staging-general1.api-api-api.com
  ssrApiUrl: http://shisha-guid-backend.shisha-guid-backend-staging.svc.cluster.local/api/v1
resources:
  requests:
    cpu: 10m
    memory: 48Mi
  limits:
    cpu: 150m
    memory: 192Mi
