_release:
  revision: 5e4632d2e4394580b92fc2a6c33f3321710a4fed
  sourceRepository: anomaly51/telegram-SwearModeration-bot
  sourceCommit: 3ba3335f2d326ce68df1c532ae542d09450e17a0
  sourceBranch: main
  runUrl: https://github.com/anomaly51/telegram-SwearModeration-bot/commit/3ba3335f2d326ce68df1c532ae542d09450e17a0
  imageKeys:
  - image
replicas: 1
image:
  repository: harbor.internal.api-api-api.com/applications/telegram-swearmoderation-bot
  tag: sha-3ba3335f2d32@sha256:2b64a71b8088bc5adab69553e4662341983d37b3cc1dc224a666c69724040fff
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi
postgresql:
  image:
    repository: postgres
    tag: 16.4-bookworm
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    storageClassName: nfs-csi
    size: 2Gi
