_release:
  policy: prod-only
  revision: e627f344be66623d0caf54b9f0fbbf6e2c0ce468
  sourceRepository: anomaly51/telegram-SwearModeration-bot
  sourceCommit: 61a71cbf61c1b85f29ec2ba4c7fd4bb86e5d5cbd
  sourceBranch: main
  runUrl: https://github.com/anomaly51/telegram-SwearModeration-bot/actions/runs/36565649436
  imageKeys:
  - image
replicas: 1
image:
  repository: harbor.internal.api-api-api.com/applications/telegram-swearmoderation-bot
  tag: sha-61a71cbf61c1@sha256:6247395decbd9d773d2119ad2e740a9d9ee011965e5cf07b76e0a828cbb7aa2d
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi
postgresql:
  image:
    repository: postgres
    tag: 16.4-bookworm
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    storageClassName: nfs-csi
    size: 2Gi
