replicaCount: 2

image:
  repository: cloudflare/cloudflared
  tag: 2026.5.0

tunnel:
  id: 4a29ced3-c1b8-4e6f-885b-8b2caaec2149

origin: https://traefik.kube-system.svc.cluster.local:443

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
