opensearch-operator:
  fullnameOverride: opensearch-operator
  legacyAPI:
    enabled: false
  nodeSelector:
    kubernetes.io/hostname: general-1-worker-1
  manager:
    watchNamespace: monitoring
    resources:
      requests: {cpu: 50m, memory: 128Mi}
      limits: {cpu: 500m, memory: 512Mi}
