apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-system-namespace.yaml
  - vault-crd-cleanup.yaml
  - project.yaml
  - applicationsets/apps.yaml
  - applicationsets/infrastructure.yaml
