apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - public-route-namespaces.yaml
  - project.yaml
  - traefik-config.yaml
  - applicationsets/apps.yaml
  - applicationsets/utility-apps.yaml
