apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
    ingressClass:
      enabled: false
    gateway:
      enabled: false
    gatewayClass:
      enabled: true
    service:
      annotations:
        metallb.io/address-pool: lan
      spec:
        loadBalancerIP: 192.168.1.3
