---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBsPQbUgDXVKvIik2UK0gAE7FRSEo18GahervS0tjiNGZPUjTpFJvOhuQ0Sx3XchnN8TJWfKbX+j+Gn4ABLCx9hJ25X6TbnKGfoDHUKrOEPLTAAloQTRVdrymHmsKl6RuCoiH8SpP2LiYODJgqt756+nDLVCeUgvR6jEDUa8nsubwWmKEaS0HbVNm5uoivjc617EiEM51EDpBq35tSg6uArAUEjdt85lwLZu7BzGooGoDIaGrEziKLMfjFWEy1SzSvIiYp36UW/Tssq1BJ5S1M5XiS7xIVgjlBQSNfqjJrjN44h1cF3F5z+RTFD+KXITE35/e/sVbAS5mNgWTETD4Jp4CxwGi6ouQodNWdrbkscG/S8e7mWx3QvM+M/FNc2kB2F2lkzGx+mN58g3qZzPQXQ8YdNGtg6XpUatHhBNAYvHEdkzk4c/LY98H6JbX1btGryeGG2VhGsmIMxNKEUrfI9ShIG1FaHgVce672atEd+L1kpEPVwYCqVNhjxRHTVMzbSyXYMSH9qACrGXOfwIJPcUTwUHIMUZlZn/HLWQeoI64tQXAnwgnQhB42iCL6qSwPAH5ZukyA2TDcUDMtJegRakOxgN6BEd6n5EBQ3lKyysQT4diZJ4rB447jjzO0KGu3r7zrlz0dIwHanrgDW88qivTObQi3kufuplXNhOUCM3UwUk6xHLJ7gW/38uXj87+clpGcWnLCD1/VknekeaoQ9dPfN2uRyJjPDRWi+/UMgBQ==
    admin-user: AgC9xMbSAa94YwWrQfGGDfg8PMAW0FzsJ0OdWxM3nN8oCmTsbcGn3fhjnTasff3I2dbyvHON08PCLIzO2tNGuerCYENitIUideAd5d4OZhN0nyUl30N1Q7qm5JP8gStnUnegUSbhsp1TLHH/styuSH7morlLGUOiRoANhIRWCsVcbWhUIOtk7BiD7RQ+H4ZfN71ZJTHr/stC2U4TnhvuN8MzArUWtbdoNK0VdI8nkXE3VfrM6njCbpQefJ0yTqxAHegmX0d7yJRaLd3chp4tJP3HmZzND0VV16CgtT/EL1EZRjeM7a3Qwv8KUDa7jYt93Kyn/zF0SlPBtRLIliGQKHY5/6geNhX/ucfA/AIaPqqApwQ+UwIjLvG36ucOY++wW9BM73oir8BMYPXJVN8+3J3Im35caFzrF6ypFip8cARFYkJhSRrx8FrXc+MvV0r4vGp+hi7WCDCalfGP2Hnl0wbGLbfkwO28GwpIS6ornPeoB4gdxEOEAHo9vE/HAF4CpAzSs05hVJ1eWIVr9KAM3B7awM3vQKeCJE1G+qSovpR3l5o4beFb2EFtPAixj18j6REGIyzjXciyiH0olhKeT1vpH7Ahboab66ve7EqZMj/wlstJvzj9rHOaYGmo0rgf+GHfptz5yIW9ZFzt+XvcZAEYDaKaSHIwyRsGIPzDgXkvrc2ULpZh8WsWNFWGSOmfowYQiQhhqQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
