apiVersion: v1
kind: Service
metadata:
  name: arc-buildkit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: arc-buildkit
  ports:
    - name: buildkit
      port: {{ .Values.buildkit.service.port }}
      targetPort: buildkit
