apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arc-buildkit-cache
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.buildkit.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.buildkit.persistence.size }}
