apiVersion: v2
name: playground-inventory-service
description: FlashDrop inventory-service production workload.
type: application
version: 0.2.0
dependencies:
  - name: app
    version: 0.6.0
    repository: oci://harbor.internal.api-api-api.com/helm-charts
