apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-wildcard
spec:
  endpoints:
    - dnsName: "*.internal.api-api-api.com"
      recordType: A
      recordTTL: 60
      targets:
        - 192.168.1.3
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
