apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barman-cloud
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: gitops-apps
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: plugin-barman-cloud
    targetRevision: 0.8.1
    helm:
      releaseName: barman-cloud
      valuesObject:
        resources:
          requests: {cpu: 50m, memory: 64Mi}
          limits: {cpu: 500m, memory: 256Mi}
  destination:
    server: https://kubernetes.default.svc
    namespace: database-system
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [ServerSideApply=true]
