apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-topology-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/rabbitmq/messaging-topology-operator.git
    targetRevision: v1.20.1
    path: config/installation
    kustomize:
      images:
        - rabbitmqoperator/messaging-topology-operator=ghcr.io/rabbitmq/messaging-topology-operator:1.20.1
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
