apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/rabbitmq/cluster-operator.git
    targetRevision: v2.22.4
    path: config/installation
    kustomize:
      images:
        - ghcr.io/rabbitmq/cluster-operator=ghcr.io/rabbitmq/cluster-operator:2.22.4
      patches:
        - target:
            kind: Deployment
            name: rabbitmq-cluster-operator
          patch: |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: rabbitmq-cluster-operator
            spec:
              strategy:
                rollingUpdate:
                  maxSurge: 0
                  maxUnavailable: 1
              template:
                spec:
                  nodeSelector:
                    node-role.kubernetes.io/control-plane: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
