apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: authentik
    serviceAccount: vault-secrets
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: authentik
  mount: kv
  type: kv-v2
  path: authentik/authentik
  refreshAfter: 1m
  destination:
    create: true
    name: postgres-app
    type: kubernetes.io/basic-auth
    transformation:
      includes:
        - ^(username|password)$
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: authentik
  mount: kv
  type: kv-v2
  path: authentik/authentik
  refreshAfter: 1m
  destination:
    create: true
    name: authentik
    transformation:
      excludes:
        - .*
      templates:
        AUTHENTIK_SECRET_KEY:
          text: '{{ `{{- get .Secrets "secret_key" -}}` }}'
        AUTHENTIK_POSTGRESQL__HOST:
          text: postgres-rw.authentik.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME:
          text: authentik
        AUTHENTIK_POSTGRESQL__USER:
          text: '{{ `{{- get .Secrets "username" -}}` }}'
        AUTHENTIK_POSTGRESQL__PASSWORD:
          text: '{{ `{{- get .Secrets "password" -}}` }}'
        AUTHENTIK_POSTGRESQL__PORT:
          text: "5432"
  rolloutRestartTargets:
    - kind: Deployment
      name: authentik-server
    - kind: Deployment
      name: authentik-worker
