csi-driver-nfs:
  controller:
    enableSnapshotter: false

  storageClass:
    create: false

  storageClasses:
    - name: nfs-csi
      parameters:
        server: 192.168.1.9
        share: /export/test
        subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
        mountPermissions: "0777"
        onDelete: retain
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true

    - name: nfs-csi-smoke
      parameters:
        server: 192.168.1.9
        share: /export/test
        subDir: "codex-smoke/${pv.metadata.name}"
        mountPermissions: "0777"
        onDelete: delete
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: false
