apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backups
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://general1-keycloak-backups/
    endpointURL: http://minio.minio-system.svc.cluster.local:9000
    s3Credentials:
      accessKeyId: {name: keycloak-backup, key: ACCESS_KEY_ID}
      secretAccessKey: {name: keycloak-backup, key: ACCESS_SECRET_KEY}
    wal: {compression: gzip}
    data: {compression: gzip}
  instanceSidecarConfiguration:
    resources:
      requests: {cpu: 50m, memory: 64Mi}
      limits: {cpu: 500m, memory: 256Mi}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-daily
spec:
  schedule: "0 0 2 * * *"
  immediate: true
  backupOwnerReference: self
  cluster: {name: postgres}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
