image:
  repository: ghcr.io/anomaly51/downloader-sloniara-bot
  tag: sha-8216e6637197547c38469c23ad4ab85c9e351185

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "2"
    memory: 2Gi
