image:
  repository: ghcr.io/anomaly51/downloader-sloniara-bot
  tag: sha-be633b3a0e3a115ecca777c8570a0550573de6d4

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 2Gi
