domain: api-api-api.com
tunnelTarget: bfaa4824-dabf-4534-8b2a-0cfa730ec2f1.cfargotunnel.com
issuer: letsencrypt-production

routes:
  - name: argocd
    namespace: argocd
    hostname: argocd.api-api-api.com
    service:
      name: argocd-server
      port: 443
      scheme: https
      insecureSkipVerify: true
  - name: grafana
    namespace: monitoring
    hostname: grafana.api-api-api.com
    service:
      name: grafana
      port: 80
      scheme: http
