apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/anomaly51/general-1-argocd.git
        revision: main
        files:
          - path: apps/*/Chart.yaml
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "60"
    spec:
      project: gitops-apps
      source:
        repoURL: https://github.com/anomaly51/general-1-argocd.git
        targetRevision: main
        path: "{{ .path.path }}"
        helm:
          releaseName: "{{ .name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .name }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
