apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: argocd-sso
            namespace: argocd
            releaseName: argocd-sso
          - name: keycloak
            namespace: keycloak
            releaseName: keycloak
          - name: nfs-provisioner
            namespace: nfs-system
            releaseName: nfs-subdir-external-provisioner
          - name: vault
            namespace: vault
            releaseName: vault
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: gitops-apps
      source:
        repoURL: https://github.com/anomaly51/general-1-argocd.git
        targetRevision: main
        path: "infrastructure/{{ .name }}"
        helm:
          releaseName: "{{ .releaseName }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
