apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: utility-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/anomaly51/general-1-argocd.git
        revision: main
        directories:
          - path: utility-apps/*/*
  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/compare-options: '{{ if eq .path.basenameNormalized "grafana" }}ServerSideDiff=false{{ else }}ServerSideDiff=true{{ end }}'
    spec:
      project: gitops-apps
      source:
        repoURL: https://github.com/anomaly51/general-1-argocd.git
        targetRevision: main
        path: "{{ .path.path }}"
        helm:
          releaseName: "{{ .path.basenameNormalized }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 1 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
