apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: utility-apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/anomaly51/general-1-argocd.git
        revision: main
        directories:
          - path: utility-apps/*/*
  template:
    metadata:
      name: '{{ if eq .path.basenameNormalized "secrets" }}{{ index .path.segments 1 }}-{{ end }}{{ .path.basenameNormalized }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: gitops-apps
      source:
        repoURL: https://github.com/anomaly51/general-1-argocd.git
        targetRevision: main
        path: "{{ .path.path }}"
        helm:
          releaseName: "{{ .path.basenameNormalized }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 1 }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
