apiVersion: v2
name: grafana
description: Pinned Grafana Community chart wrapper.
type: application
version: 0.3.0
dependencies:
  - name: grafana
    version: 12.10.1
    repository: https://grafana-community.github.io/helm-charts
