_release:
  revision: 6615fac4c310c777564e71db87577e9473822aae
  sourceRepository: anomaly51/job-application-crm
  sourceCommit: 7c9dd54fae982f72c1fb346ad065a1681ab97f19
  sourceBranch: dev
  runUrl: https://github.com/anomaly51/job-application-crm/actions/runs/36480986381
  imageKeys:
  - images.api
  - images.frontend
images:
  api:
    repository: harbor.internal.api-api-api.com/applications/job-application-crm-api
    tag: sha-7c9dd54fae98@sha256:5c6366553c035daff5fc941c316afeb3ee5ba1bdb823e8f46d2b06b23b3251be
    pullPolicy: IfNotPresent
  frontend:
    repository: harbor.internal.api-api-api.com/applications/job-application-crm-frontend
    tag: sha-7c9dd54fae98@sha256:0e5c69d5bb3f80515c82d7644252e0c9e76dea923a283599ab96c780123ecc4e
    pullPolicy: IfNotPresent
  postgres:
    repository: docker.io/library/postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
registry:
  server: harbor.internal.api-api-api.com
  vaultPath: apps/job-application-crm/dev/registry
vault:
  mount: kv
  authMount: kubernetes
  role: job-application-crm-dev
  envPath: apps/job-application-crm/dev/env
  refreshAfter: 1m
routes:
  gatewayName: public
  gatewayNamespace: networking
  gatewaySectionName: https
  frontendHostname: job-crm-dev-general1.api-api-api.com
  apiHostname: job-crm-api-dev-general1.api-api-api.com
storage:
  className: nfs-csi
  postgresSize: 2Gi
resources:
  api:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
  migration:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 192Mi
  frontend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  postgres:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 384Mi
