_release:
  revision: a1ed19f3f3c8bbfbddae37a82d6e2f4a0a0e4e44
  sourceRepository: anomaly51/job-application-crm
  sourceCommit: 7c9dd54fae982f72c1fb346ad065a1681ab97f19
  sourceBranch: main
  runUrl: https://github.com/anomaly51/job-application-crm/actions/runs/36480982962
  imageKeys:
  - images.api
  - images.frontend
images:
  api:
    repository: harbor.internal.api-api-api.com/applications/job-application-crm-api
    tag: sha-7c9dd54fae98@sha256:b9952173da9beb6c653fad3129eb2d49aabef534111f7ae8392eb0df4ec37120
    pullPolicy: IfNotPresent
  frontend:
    repository: harbor.internal.api-api-api.com/applications/job-application-crm-frontend
    tag: sha-7c9dd54fae98@sha256:1f09d5f8dfe66dccbfde61193f45cb3fc49e67c90e13410dea85d06d43c652f2
    pullPolicy: IfNotPresent
  postgres:
    repository: docker.io/library/postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
registry:
  server: harbor.internal.api-api-api.com
  vaultPath: apps/job-application-crm/staging/registry
vault:
  mount: kv
  authMount: kubernetes
  role: job-application-crm-staging
  envPath: apps/job-application-crm/staging/env
  refreshAfter: 1m
routes:
  gatewayName: public
  gatewayNamespace: networking
  gatewaySectionName: https
  frontendHostname: job-crm-staging-general1.api-api-api.com
  apiHostname: job-crm-api-staging-general1.api-api-api.com
storage:
  className: nfs-csi
  postgresSize: 2Gi
resources:
  api:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
  migration:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 192Mi
  frontend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  postgres:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 384Mi
