apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-shop-fastapi-uploads
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.uploadsSize }}
