_release:
  policy: prod-only
  sourceRepository: anomaly51/downloader_sloniara_bot
  revision: ccd32793828376539a29048135f6069da9994d6e
  sourceCommit: 6c902174be562f6ce4e1bb87c80db0fcd8c98b72
  sourceBranch: main
  runUrl: https://github.com/anomaly51/downloader_sloniara_bot/actions/runs/36565646694
  imageKeys:
  - image
image:
  repository: ghcr.io/anomaly51/downloader-sloniara-bot
  tag: sha-6c902174be56@sha256:4eb5ecbff027165f516d3ca9afda820de7ad8fd0c1bffa699a531e30f2981210
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: '2'
    memory: 2Gi
