_release:
  revision: 9776ef646e60e01819a389eafe49a6d61f31e7b9
  sourceRepository: anomaly51/Online_SHOP-FastAPI
  sourceCommit: 03968a62e33ec8737b7dde3accd9546360d166f2
  sourceBranch: dev
  runUrl: https://github.com/anomaly51/Online_SHOP-FastAPI/actions/runs/36480942410
  imageKeys:
  - images.backend
  - images.frontend
replicas:
  backend: 1
  frontend: 1
images:
  backend:
    repository: harbor.internal.api-api-api.com/applications/online-shop-fastapi
    tag: sha-03968a62e33e@sha256:59a14be3d4065d581094119f95359f1cf9628407590ec77a1fdd23f50d9b5ff6
    pullPolicy: IfNotPresent
  frontend:
    repository: harbor.internal.api-api-api.com/applications/online-shop-frontend
    tag: sha-03968a62e33e@sha256:7bef83b6cf417a7535b474acdd2d9092d44cb1a87b5109da9615750b2a0430d5
    pullPolicy: IfNotPresent
  postgres:
    repository: docker.io/library/postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
registry:
  server: harbor.internal.api-api-api.com
  vaultPath: apps/online-shop-fastapi/dev/registry
vault:
  mount: kv
  authMount: kubernetes
  role: online-shop-fastapi-dev
  envPath: apps/online-shop-fastapi/dev/env
  refreshAfter: 1m
routes:
  gatewayName: public
  gatewayNamespace: networking
  gatewaySectionName: https
  frontendHostname: online-shop-dev-general1.api-api-api.com
  apiHostname: online-shop-api-dev-general1.api-api-api.com
services:
  backend:
    port: 80
    containerPort: 8000
  frontend:
    port: 80
    containerPort: 80
storage:
  className: nfs-csi
  postgresSize: 2Gi
  uploadsSize: 2Gi
resources:
  backend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 320Mi
  migration:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 192Mi
  frontend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  postgres:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 384Mi
