_release:
  revision: c16b25ad154da0e315e0b0875fdc71ce326b7198
  sourceRepository: anomaly51/Online_SHOP-FastAPI
  sourceCommit: 03968a62e33ec8737b7dde3accd9546360d166f2
  sourceBranch: main
  runUrl: https://github.com/anomaly51/Online_SHOP-FastAPI/actions/runs/36480939469
  imageKeys:
  - images.backend
  - images.frontend
replicas:
  backend: 1
  frontend: 1
images:
  backend:
    repository: harbor.internal.api-api-api.com/applications/online-shop-fastapi
    tag: sha-03968a62e33e@sha256:eb2e7b009b862fc93d696ca3f0ba1a6a4ed62b94bb31ddfffe54ca9230953edf
    pullPolicy: IfNotPresent
  frontend:
    repository: harbor.internal.api-api-api.com/applications/online-shop-frontend
    tag: sha-03968a62e33e@sha256:c8b7eef2b38cb2becde873e7e09ffd846886cb9951f5a34362eeca1547965cf7
    pullPolicy: IfNotPresent
  postgres:
    repository: docker.io/library/postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
registry:
  server: harbor.internal.api-api-api.com
  vaultPath: apps/online-shop-fastapi/staging/registry
vault:
  mount: kv
  authMount: kubernetes
  role: online-shop-fastapi-staging
  envPath: apps/online-shop-fastapi/staging/env
  refreshAfter: 1m
routes:
  gatewayName: public
  gatewayNamespace: networking
  gatewaySectionName: https
  frontendHostname: online-shop-staging-general1.api-api-api.com
  apiHostname: online-shop-api-staging-general1.api-api-api.com
services:
  backend:
    port: 80
    containerPort: 8000
  frontend:
    port: 80
    containerPort: 80
storage:
  className: nfs-csi
  postgresSize: 2Gi
  uploadsSize: 2Gi
resources:
  backend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 320Mi
  migration:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 192Mi
  frontend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  postgres:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 384Mi
