product: bot-motivation
environment: prod
enabled: 'true'
namespace: apps
components:
- component: app
  applicationName: apps-bot-motivation
  releaseName: bot-motivation
  chartRepo: https://github.com/anomaly51/general-1-argocd.git
  chartRevision: ccd32793828376539a29048135f6069da9994d6e
  chartPath: apps/bot-motivation
  chartName: ''
  releaseValues:
    image:
      repository: harbor.internal.api-api-api.com/applications/bot-motivation
      tag: sha-2b54a1ae7a59
      pullPolicy: IfNotPresent
