apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: monitoring
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: monitoring
    serviceAccount: vault-secrets
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin
spec:
  vaultAuthRef: monitoring
  mount: kv
  type: kv-v2
  path: monitoring/grafana
  refreshAfter: 1m
  destination:
    create: true
    name: grafana-admin
  rolloutRestartTargets:
    - kind: Deployment
      name: grafana
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pve-credentials
spec:
  vaultAuthRef: monitoring
  mount: kv
  type: kv-v2
  path: monitoring/pve-exporter
  refreshAfter: 1m
  destination:
    create: true
    name: pve-credentials
  rolloutRestartTargets:
    - kind: Deployment
      name: pve-exporter
