{{- define "authentik.directEnv" -}}
- name: AUTHENTIK_BOOTSTRAP_EMAIL
  value: "akadmin@example.invalid"
- name: AUTHENTIK_BOOTSTRAP_PASSWORD
  value: "6c2f7234bf231afffc8a546dabbe6d8f"
- name: AUTHENTIK_ERROR_REPORTING__ENABLED
  value: "false"
- name: AUTHENTIK_POSTGRESQL__HOST
  value: "authentik-postgresql.authentik.svc.cluster.local"
- name: AUTHENTIK_POSTGRESQL__NAME
  value: "authentik"
- name: AUTHENTIK_POSTGRESQL__PASSWORD
  value: "73625f199dfb5a713fd35a850a9356cd95939beeeb5825f1"
- name: AUTHENTIK_POSTGRESQL__USER
  value: "authentik"
- name: AUTHENTIK_SECRET_KEY
  value: "6987bec4b796e5261e4564f408ea4dfc4a57ee69aff2121ee17ac603d8604354"
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: authentik-server
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: authentik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: 9000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: authentik
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/instance: authentik
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: authentik
    spec:
      automountServiceAccountToken: false
      containers:
        - name: server
          image: ghcr.io/goauthentik/server:2026.5.6
          imagePullPolicy: IfNotPresent
          args:
            - server
          env:
            {{- include "authentik.directEnv" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: metrics
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/health/ready/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /-/health/live/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: authentik
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/instance: authentik
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: authentik
    spec:
      automountServiceAccountToken: false
      containers:
        - name: worker
          image: ghcr.io/goauthentik/server:2026.5.6
          imagePullPolicy: IfNotPresent
          args:
            - worker
          env:
            {{- include "authentik.directEnv" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: metrics
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - ak
                - healthcheck
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - ak
                - healthcheck
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - ak
                - healthcheck
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 60
