image:
  repository: moby/buildkit
  tag: v0.32.2
  pullPolicy: IfNotPresent
persistence:
  storageClassName: local-path
  size: 30Gi
service:
  port: 1234
nodeSelector:
  kubernetes.io/hostname: general-1-worker-3
resources:
  requests:
    cpu: 250m
    memory: 512Mi
    ephemeral-storage: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi
    ephemeral-storage: 2Gi
buildkit:
  maxParallelism: 2
  reservedSpace: 2GB
  maxUsedSpace: 20GB
  minFreeSpace: 10GB
