prometheus-pve-exporter:
  nameOverride: pve-exporter
  fullnameOverride: pve-exporter

  image:
    registry: ghcr.io
    repository: prometheus-pve/prometheus-pve-exporter
    tag: "3.9.0"
    pullPolicy: IfNotPresent

  replicaCount: 1
  revisionHistoryLimit: 10

  serviceAccount:
    create: true
    name: pve-exporter

  args:
    - --collector.pve-api-metrics
    - --collector.target-metrics

  env:
    pveAuthType: token
    pveUser: "prometheus@pve"
    pveExistingSecretName: pve-credentials
    pveVerifySsl: false

  service:
    type: ClusterIP
    port: 9221

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsGroup: 101
    runAsNonRoot: true
    runAsUser: 101
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

  serviceMonitor:
    enabled: false
