apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secret.name is required" .Values.secret.name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ required (printf "secret.data.%s is required" $key) $value | quote }}
  {{- end }}
