external-dns:
  provider:
    name: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token
  sources:
    - ingress
  domainFilters:
    - api-api-api.com
  policy: sync
  registry: txt
  txtOwnerId: general-1-k3s
  interval: 1m
  extraArgs:
    - --cloudflare-proxied
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
