apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-monitoring
  namespace: monitoring
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: monitoring
spec:
  address: http://vault.vault-system.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: monitoring
  namespace: monitoring
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: monitoring
    serviceAccount: vso-monitoring
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  vaultAuthRef: monitoring
  mount: kv
  type: kv-v2
  path: monitoring/grafana-admin
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    name: grafana-admin
    create: false
    transformation:
      excludeRaw: true
  rolloutRestartTargets:
    - kind: Deployment
      name: grafana
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  vaultAuthRef: monitoring
  mount: kv
  type: kv-v2
  path: monitoring/pve-exporter
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    name: pve-exporter
    create: false
    transformation:
      excludeRaw: true
  rolloutRestartTargets:
    - kind: Deployment
      name: pve-exporter
