apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-monitoring
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
spec:
  address: http://vault.vault-system.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: monitoring
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: monitoring
    serviceAccount: vso-monitoring
    audiences:
      - vault
    tokenExpirationSeconds: 600
