apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false,Delete=false
data:
  application.sync.requireOverridePrivilegeForRevisionSync: "true"
  url: {{ .Values.argocd.url | quote }}
  additionalUrls: |
{{ toYaml .Values.argocd.additionalUrls | indent 4 }}
  oidc.config: |
    name: Keycloak
    issuer: {{ .Values.keycloak.issuer }}
    clientID: {{ .Values.keycloak.clientID }}
    enablePKCEAuthentication: true
    refreshTokenThreshold: 2m
    requestedScopes: ["openid", "groups"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false,Delete=false
data:
  policy.default: role:authenticated
  policy.csv: |
    g, {{ .Values.rbac.adminGroup }}, role:admin
    g, {{ .Values.rbac.readonlyGroup }}, role:readonly
  scopes: '[groups]'
